### ISSUE TITLE
[1.7.10] Cascading worldgen false positive

### ISSUE THREAD

**Issue by quentin452** [Red-Studio-Ragnarok/Red-Core#8]
## Describe the bug

***A clear and concise description of what the bug is.***

I Got Cascading worldgen in Logs , he say Red Core but it should say the Mod name that make the cascading

## Reproducibility

Don't have time to reproduce the issue with Cascading worldgen log debugging from Archaicfix for now

- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Really idk just generate world

## Expected behavior

***A clear and concise description of what you expected to happen.***
Cascading worldgen shouldn't appear

## Screenshots or/and videos

***If applicable, add screenshots and/or videos to help explain your problem.***

![image](https://github.com/Red-Studio-Ragnarok/Red-Core/assets/42176772/47ad9f08-69a0-444c-9496-9e4ce0a9e7ba)

## Logs or/and crash reports

***Please use https://mclo.gs/ to upload your logs and crash reports***

https://mclo.gs/ZNd5NK1

## Versions

- Red Core Version: !Red-Core-MC-1.7-1.12-0.5.1
- Forge: 1.7.10 - 10.13.4.1614
- Java: update392 x64
- Java JVM: AZUL ZULU

## Specification:

- OS: Windows10
- CPU: I5 10400f
- GPU: RTX 3060
- RAM Allocated: 8192mb

***All of these info below are not necessary but may become necessary depending on the issue***

- CPU Speed: 2.9GHz, 4.30 GHz boost
- CPU Core: 6
- CPU Threads: 12
- RAM Size: 32GB
- RAM Speed: 2666MHz
- Storage Type: 1 TO ssd
- GPU VRAM: 12GB

**Comment by quentin452** [comment]
it seem thats false positive, i enabled CascadingworldgenStacktrace in archaicfix and is not caused by Red Core (but why Red Core is written???) at the top has "Red Core loaded a new chunk" but normally it should say "Et Futurum Requiem Loaded a new chunk"

![image](https://github.com/Red-Studio-Ragnarok/Red-Core/assets/42176772/e28a3257-a055-40df-b08a-c155018050ba)

**Comment by Desoroxxx** [comment]
Yeah that is weird, Red Core does nothing on it's own

**Comment by Desoroxxx** [comment]
I have no idea how to fix this while still being able to have Red Core on multiple versions at once

**Comment by strubium** [comment]
> it seem thats false positive, i enabled CascadingworldgenStacktrace in archaicfix and is not caused by Red Core ,but why Red Core is written at the top has "Red Core loaded a new chunk" but normally it should say "Et Futurum Requiem Loaded a new chunk"
> 
> ![image](https://private-user-images.githubusercontent.com/42176772/285058462-e28a3257-a055-40df-b08a-c155018050ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NzM0NDMsIm5iZiI6MTcxMTU3MzE0MywicGF0aCI6Ii80MjE3Njc3Mi8yODUwNTg0NjItZTI4YTMyNTctYTA1NS00MGRmLWIwOGEtYzE1NTAxODA1MGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDIwNTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ODM1NDNmM2ZiOGEyNjg0NTQzYTQyOTliNWI3ZmJkZGQyMWM1YzU1M2RlZGJlNjBjZTQ3YmY0NGYwMjUyMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fiamxzs9r2TNV1XePQxotDV8F2bQgATGci7n1gZVOIQ)

Had a similar issue with Simple Voice Chat on 1.12.2, will try to find a screenshot

**Comment by Desoroxxx** [comment]
Fixed in [Red Core 0.6 Dev 3](https://www.curseforge.com/minecraft/mc-mods/red-core/files/5163117)

**Comment by ArtpokeBr** [comment]
Is this still a thing?
